# 3.1 DataFrame Type 소개

Pandas 라는 패키지를 이용해서 DataFrame이라는 데이터 타입을 사용할 수 있다.

DataFrame 장점 : 데이터를 한 눈에 파악하기 쉽다. 다양한 데이터 전처리 함수들이 있기에, 전처리하기 용이하다.
    
DataFrame 단점 : 연산속도가 너무 느리고, 메모리를 너무 많이 차지한다.

### 3.1.1 Pandas 패키지 불러오기 및 DataFrame 생성

In [1]:
List_data= [ [1,2,3,4] , [5,6,7,8] ]
List_data

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [2]:
import pandas as pd

위의 함수는 패키지라는 함수를 불러오고(사용할 준비) pd라고 줄여서 사용하겠다는 의미이다.

In [3]:
df_data=pd.DataFrame(List_data)
df_data

0  1  2  3
0  1  2  3  4
1  5  6  7  8

세로축 name 은 index , 가로축 name 은 columns 이라고 부른다.

###  ● Series Data Type

In [5]:
Se_data=[1,2,3,4]
Se_data

[1, 2, 3, 4]

In [6]:
pd.Series(Se_data)

0    1
1    2
2    3
3    4
dtype: int64

### 3.1.2 DataFrame 특징

In [7]:
df_data

0  1  2  3
0  1  2  3  4
1  5  6  7  8

###  ● describe()

In [8]:
df_data.describe()

0         1         2         3
count  2.000000  2.000000  2.000000  2.000000
mean   3.000000  4.000000  5.000000  6.000000
std    2.828427  2.828427  2.828427  2.828427
min    1.000000  2.000000  3.000000  4.000000
25%    2.000000  3.000000  4.000000  5.000000
50%    3.000000  4.000000  5.000000  6.000000
75%    4.000000  5.000000  6.000000  7.000000
max    5.000000  6.000000  7.000000  8.000000

각 열에 대한 기초통계량들을 보여준다

###  ● iloc

In [19]:
df_data

a1  a2   a3  a4
aa   1   2  100   4
bb   5   6    7   8

In [15]:
df_data.columns = ["a1","a2","a3","a4"]

In [18]:
df_data.index = ["aa","bb"]

In [20]:
df_data.iloc[0,2] 

100

In [11]:
df_data.iloc[0,0]

1

즉, df_data.iloc[a,b]    =>    df_data 에서 a,b 성분을 반환해준다.

In [22]:
df_data.iloc[:,0] 

aa    1
bb    5
Name: a1, dtype: int64

In [23]:
pd.DataFrame(df_data.iloc[:,0]) 

a1
aa   1
bb   5

세미콜론 : 은 전체를 의미한다. 
    
즉, 위의 코드는 0번째 column 전체 데이터를 반환해주는 코드이다.

▶참고


위의 처럼, 두개 이상의 데이터를 불러오게 되면 Series Type 으로 반환을 해준다. 

####  ● DataFrame Type의 columns 과 index

In [24]:
df_data

a1  a2   a3  a4
aa   1   2  100   4
bb   5   6    7   8

In [25]:
df_data.columns = ["a1","a2","a3","a4"]

In [26]:
df_data.columns[0]

'a1'

In [27]:
df_data.columns[1]

'a2'

In [28]:
df_data.index = ["A","B"]

In [29]:
df_data

a1  a2   a3  a4
A   1   2  100   4
B   5   6    7   8

In [30]:
df_data.index[0]

'A'

In [31]:
df_data

a1  a2   a3  a4
A   1   2  100   4
B   5   6    7   8

###  ● loc 

In [32]:
df_data.loc["A","a1"]

1

df_data.loc[1,"b"] 은 columns "b"열에서 index 1에 해당되는 것을 가져오는 것을 말한다. 

###  ● loc 와 iloc의 차이  

iloc는 순서를 기준으로 가져오는 것이고, loc는 colums 과 index의 이름을 기준으로 가져온다.

In [53]:
df_data.iloc[1,0]

5

In [55]:
df_data.loc[1,"a"]

1

###  ● []을 이용한 방법

In [33]:
df_data

a1  a2   a3  a4
A   1   2  100   4
B   5   6    7   8

In [34]:
df_data["a1"]

A    1
B    5
Name: a1, dtype: int64

In [36]:
df_data["a1"].values

array([1, 5], dtype=int64)

### 예제 3.1

In [3]:
import pandas as pd

In [4]:
x=pd.DataFrame( [[1,2,3,4,10],[6,7,8,9,5]])
x

0  1  2  3   4
0  1  2  3  4  10
1  6  7  8  9   5

위와 같은 DataFrame이 있을때, 모든 성분을 1로 바꾸어라. 

In [5]:
x[:] = 1
x

0  1  2  3  4
0  1  1  1  1  1
1  1  1  1  1  1

Sol)

In [39]:
for i in range(0,5):       #i는 column에 대한 순서를 의미
    for j in range(0,2):   #j는 index에 대한 순서를 의미
        
        x.iloc[j,i] = 1    

###  ● sort_values()

In [38]:
df=pd.DataFrame( [[1,2,3,4,10],[6,7,8,9,5]])
df.columns = ["a","b","c","d","e"]
df

a  b  c  d   e
0  1  2  3  4  10
1  6  7  8  9   5

In [72]:
df.sort_values(by="e")

a  b  c  d   e
1  6  7  8  9   5
0  1  2  3  4  10

위의 코드는 "e" 라는 열 기준으로 오름차순으로 정렬하는 것을 의미한다.


In [39]:
df.sort_values(by="e", ascending=False)

a  b  c  d   e
0  1  2  3  4  10
1  6  7  8  9   5

###  ● value_counts()

In [41]:
df=pd.DataFrame([["A","B"]*3,["A","B","C"]*2,["A","C","D"]*2])
df

0  1  2  3  4  5
0  A  B  A  B  A  B
1  A  B  C  A  B  C
2  A  C  D  A  C  D

In [42]:
df.iloc[:,1]

0    B
1    B
2    C
Name: 1, dtype: object

In [43]:
df.iloc[:,1].value_counts()

B    2
C    1
Name: 1, dtype: int64

위의 코드는 df 에서 첫번째 columns 에서 각 데이터에 대하여 빈도수를 알려주는 코드이다. 

###  ● get_dummies()

In [44]:
ge_data = df.iloc[:,1]

In [45]:
ge_data

0    B
1    B
2    C
Name: 1, dtype: object

In [46]:
pd.get_dummies(ge_data)

B  C
0  1  0
1  1  0
2  0  1

위의 코드는 one-hot encoding 즉, 위의 처럼 각 데이터에 대하여 있고 없음을 0과1로 표현해준다.

데이터 분석에서, "명목형 변수" 데이터를 분석할때 자주 사용된다.

###  ● groupby()

In [47]:
df=pd.DataFrame([[1,2,3,4],[5,6,7,8],[1,4,2,3]])
df.columns=["a","b","c","d"]
df

a  b  c  d
0  1  2  3  4
1  5  6  7  8
2  1  4  2  3

In [48]:
df.groupby("a").sum()

b  c  d
a         
1  6  5  7
5  6  7  8

In [49]:
df.groupby("a").mean()

b    c    d
a               
1  3.0  2.5  3.5
5  6.0  7.0  8.0

위의 .sum() 함수는 

df 에서 a column 의 unique() 원소 기준에 따라서 더 해준다.

위의 .mean() 함수는 

df 에서 a column 의 unique() 원소 기준에 따라서 평균을 내준다.

▶참고

위에서 배운 DataFrame 들에 대한 많은 함수들은 데이터 분석할때 굉장히 자주 사용되는 함수들이다.

### 예제 3.2

In [6]:
df=pd.DataFrame([["A","B"]*3,["A","B","C"]*2,["A","C","D"]*2,["E","A"]*3])
df

0  1  2  3  4  5
0  A  B  A  B  A  B
1  A  B  C  A  B  C
2  A  C  D  A  C  D
3  E  A  E  A  E  A

위의 데이터에서 A = 1 , B = 2 , C = 3, D = 4, E = 5 으로 대체해라.

In [18]:
df = df.replace("A", 1)
df = df.replace("B", 2)
df = df.replace("C", 3)
df = df.replace("D", 4)
df = df.replace("E", 5)
df

0  1  2  3  4  5
0  1  2  1  2  1  2
1  1  2  3  1  2  3
2  1  3  4  1  3  4
3  5  1  5  1  5  1

In [59]:
for i in range(0,6):
    for j in range(0,4):
        
        if df.iloc[j,i] =="A":
            df.iloc[j,i] = 1
    

In [60]:
df

0  1  2  3  4  5
0  1  B  1  B  1  B
1  1  B  C  1  B  C
2  1  C  D  1  C  D
3  E  1  E  1  E  1

### 예제 3.3 

In [20]:
df=pd.DataFrame([["A","B"]*3,["A","B","C"]*2,["A","C","D"]*2,["E","A"]*3])
df

0  1  2  3  4  5
0  A  B  A  B  A  B
1  A  B  C  A  B  C
2  A  C  D  A  C  D
3  E  A  E  A  E  A

In [21]:
df = df.replace("A", 1)
df

0  1  2  3  4  5
0  1  B  1  B  1  B
1  1  B  C  1  B  C
2  1  C  D  1  C  D
3  E  1  E  1  E  1

위의 데이터에서 A만 1로 대체해라.

### 예제 3.4

In [22]:
df=pd.DataFrame([["A","B"]*3,["A","B","C"]*2,["A","C","D"]*2,["E","A"]*3])
df

0  1  2  3  4  5
0  A  B  A  B  A  B
1  A  B  C  A  B  C
2  A  C  D  A  C  D
3  E  A  E  A  E  A

다섯번째 열 기준으로 오름차순으로 나열해라.

In [25]:
df.sort_values(4, ascending =False)

0  1  2  3  4  5
3  E  A  E  A  E  A
2  A  C  D  A  C  D
1  A  B  C  A  B  C
0  A  B  A  B  A  B

In [64]:
df.sort_values(by=5)

0  1  2  3  4  5
3  E  A  E  A  E  A
0  A  B  A  B  A  B
1  A  B  C  A  B  C
2  A  C  D  A  C  D

### 예제 3.5

In [65]:
df=pd.DataFrame([["A","B"]*3,["A","B","C"]*2,["A","C","D"]*2,["E","A"]*3 , ["A","B"]*3,["A","B","C"]*2,["A","C","D"]*2,["E","A"]*3  ])
df

0  1  2  3  4  5
0  A  B  A  B  A  B
1  A  B  C  A  B  C
2  A  C  D  A  C  D
3  E  A  E  A  E  A
4  A  B  A  B  A  B
5  A  B  C  A  B  C
6  A  C  D  A  C  D
7  E  A  E  A  E  A

위의 데이터의 각 열에 대하여 각 알파벳들의 빈도수를 구하여라.

In [68]:
df[0].value_counts()

A    6
E    2
Name: 0, dtype: int64

In [69]:
df[1].value_counts()

B    4
C    2
A    2
Name: 1, dtype: int64

In [70]:
df[2].value_counts()

A    2
C    2
D    2
E    2
Name: 2, dtype: int64

# 3.2 Numpy Type 소개

## 3.2.1 Numpy 탄생한 배경

파이썬은 수치계산이 굉장히 느린 단점이 있다.

이를 해결하기 위해 탄생한 것이 Numpy 패키지이다.

Numpy는 수치계산이 굉장히 빠르게 되는 type이고, 다양한 수치계산 함수들이 있다.

## 3.2.2 Numpy 특징

In [51]:
import numpy as np

In [52]:
A=[ [3,4,5,6], [10,11,12,13] ]
A_np=np.array(A)

In [53]:
A

[[3, 4, 5, 6], [10, 11, 12, 13]]

In [54]:
A_np

array([[ 3,  4,  5,  6],
       [10, 11, 12, 13]])

### ● Shape

In [55]:
np.shape(A_np)

(2, 4)

np type인 A_np 의 데이터 크기를 알려주는 함수이다.

## ● zeros 와 ones

In [58]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [59]:
np.zeros([10,10])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [60]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [61]:
np.ones([10,10])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## ● random 함수

In [74]:
np.random.random(2)

array([0.8139468 , 0.87812911])

0과 1사이의 임의의 난수를 2개 생성해주는 함수이다.

In [88]:
np.random.randint(0,10) #0과 9사이의 정수를 랜덤으로 추출합니다. 

2

In [99]:
np.random.randint(0,10,2)

array([8, 2])

np.random.randint(a,b,c) 는 a와b-1 사이의 정수 중에 c개 추출하는 함수이다. 

## ● arange 함수

In [103]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

0부터 9까지 나열하는 함수를 말한다. 

## ● 사칙연산

1. 덧셈

In [106]:
A

array(3)

In [107]:
B

array(4)

In [105]:
A=np.array(3)
B=np.array(4)

A+B

7

In [109]:
A

array([1, 2, 3])

In [110]:
B

array([10, 11, 12])

In [108]:
A=np.array([1,2,3])
B=np.array([10,11,12])

A+B

array([11, 13, 15])

뺄셈 역시 덧셈과 동일하므로 생략한다.

2. 곱셈

In [111]:
A

array([1, 2, 3])

In [112]:
B

array([10, 11, 12])

In [114]:
A*B

array([10, 22, 36])

3. 행렬곱

In [115]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

In [116]:
A

array([[1, 2],
       [3, 4]])

In [117]:
B

array([[5, 6],
       [7, 8]])

In [118]:
A.dot(B)

array([[19, 22],
       [43, 50]])

## ● mean, sum, min, max ,var, std

In [119]:
A

array([[1, 2],
       [3, 4]])

In [120]:
np.mean(A)

2.5

In [121]:
np.sum(A)

10

In [122]:
np.min(A)

1

In [123]:
np.max(A)

4

In [124]:
np.var(A)

1.25

In [125]:
np.std(A)

1.118033988749895

## ● vstack 과 hstack

In [126]:
A

array([[1, 2],
       [3, 4]])

In [127]:
B

array([[5, 6],
       [7, 8]])

In [128]:
np.vstack((A,B))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [129]:
np.hstack((A,B))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### 예제 3.6

In [26]:
import numpy as np

In [27]:
x = np.array([[1,2,3,4],[5,6,7,8]])
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

이때 5이하의 성분을 모두 0으로 바꾸어라. 

In [28]:
x[x<=5] = 0
x

array([[0, 0, 0, 0],
       [0, 6, 7, 8]])

In [170]:
x[0,0]

1

In [177]:
x[x <= 5] = 1

In [178]:
x

array([[1, 1, 1, 1],
       [1, 6, 7, 8]])

### 예제 3.7

np.array 을 DataFrame으로 바꾸어주는 함수를 만들어라. 

In [30]:
from numpy import random

data_array = random.randint(100, size=(4,3))
print(data_array)

[[95 19 65]
 [ 5 89 29]
 [85 93 85]
 [77 13 78]]


In [35]:
df = pd.DataFrame(data_array)
df

0   1   2
0  95  19  65
1   5  89  29
2  85  93  85
3  77  13  78